services:
  duckdb:
    container_name: duckdb
    build:
      context: ./datesets_static/
    volumes:
      - ./tmp/duckdb/data:/app/data
    stdin_open: true
    tty: true
    ports:
      - "5000:5000"
  analytics:
    container_name: analytics
    build:
      context: ./analytics/
    volumes:
      - ./tmp/analytics:/lytics/
    stdin_open: true
    tty: true
    ports:
      - "5001:5001"
