
sources:
  - name: my_duckdb_file
    description: "Source data for dbt transformations"
    tables:
      - name: fortune_500
        description: "Raw Fortune 500 data"
      - name: weather_data
        description: "Raw NOAA weather data"