version: 2

sources:
  - name: data  # A logical name for your source
    schema: main                # Schema where the table resides (use `main` for DuckDB)
    tables:
      - name: business          # Name of the table in your database
        description: "Raw business data"
  - name: data
    schema: main
    tables:
    - name: weather
      description: "Raw weather data"
