name: 'my_dbt_project'
version: '1.0.0'

profile: 'my_dbt_project'  # Matches profiles.yml

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Define the packages-install-path explicitly
packages-install-path: "/dbt/dbt_packages"

clean-targets:       
  - "target"
  - "dbt_packages"

models:
  my_dbt_project:
    +schema: transformed
    +materialized: table

sources:
 +schema: main
 +database: ''
