name: 'my_dbt_project'
version: '1.0.0'

profile: 'my_dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:       
  - "target"
  - "dbt_packages"

models:
  my_dbt_project:
    target: dev
    outputs:
      dev:
        type: duckdb
        path: ./data/my_duckdb_file.db  # Path to your DuckDB file
        threads: 1

vars:
  duckdb_database: './data/my_duckdb_file.db'


